config/routes.rb
Rails.application.routes.draw do
  resources :artisans

  resources :users

  get 'home/index'
  root 'home#index'

end

app/models/artisan.rb
class Artisan < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artisans_controller.rb
class ArtisansController < ApplicationController
  before_action :set_artisan, only: [:show, :edit, :update, :destroy]

  # GET /artisans
  # GET /artisans.json
  def index
    @artisans = Artisan.all
  end

  # GET /artisans/1
  # GET /artisans/1.json
  def show
  end

  # GET /artisans/new
  def new
    @artisan = Artisan.new
  end

  # GET /artisans/1/edit
  def edit
  end

  # POST /artisans
  # POST /artisans.json
  def create
    @artisan = Artisan.new(artisan_params)

    respond_to do |format|
      if @artisan.save
        format.html { redirect_to @artisan, notice: 'Artisan was successfully created.' }
        format.json { render :show, status: :created, location: @artisan }
      else
        format.html { render :new }
        format.json { render json: @artisan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artisans/1
  # PATCH/PUT /artisans/1.json
  def update
    respond_to do |format|
      if @artisan.update(artisan_params)
        format.html { redirect_to @artisan, notice: 'Artisan was successfully updated.' }
        format.json { render :show, status: :ok, location: @artisan }
      else
        format.html { render :edit }
        format.json { render json: @artisan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artisans/1
  # DELETE /artisans/1.json
  def destroy
    @artisan.destroy
    respond_to do |format|
      format.html { redirect_to artisans_url, notice: 'Artisan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artisan
      @artisan = Artisan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artisan_params
      params.require(:artisan).permit(:description, :firstname, :lastname, :society, :phone, :location)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:firstname, :lastname, :phone, :mail, :location, :cardnumber, :carddate, :cardback)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artisans_helper.rb
module ArtisansHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/artisans/_form.html.erb
<%= form_for @artisan, :html => { :class => "form-horizontal artisan" } do |f| %>

    <% if @artisan.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@artisan.errors.count, "error") %> prohibited this artisan from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @artisan.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%= error_span(@artisan[:description]) %>
  </div>
  <div class="control-group">
    <%= f.label :firstname, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :firstname, :class => 'form-control' %>
    </div>
    <%= error_span(@artisan[:firstname]) %>
  </div>
  <div class="control-group">
    <%= f.label :lastname, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :lastname, :class => 'form-control' %>
    </div>
    <%= error_span(@artisan[:lastname]) %>
  </div>
   <div class="control-group">
    <%= f.label :society, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :society, :class => 'form-control' %>
    </div>
    <%= error_span(@artisan[:society]) %>
  </div>
  <div class="control-group">
    <%= f.label :phone, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :phone, :class => 'form-control' %>
    </div>
    <%= error_span(@artisan[:phone]) %>
  </div>
  <div class="control-group">
    <%= f.label :location, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :location, :class => 'form-control' %>
    </div>
    <%= error_span(@artisan[:location]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            artisans_path, :class => 'btn btn-default' %>

<% end %>

app/views/artisans/edit.html.erb
<%- model_class = Artisan -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/artisans/index.html.erb
<%- model_class = Artisan -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:firstname) %></th>
      <th><%= model_class.human_attribute_name(:lastname) %></th>
      <th><%= model_class.human_attribute_name(:society) %></th>
      <th><%= model_class.human_attribute_name(:phone) %></th>
      <th><%= model_class.human_attribute_name(:location) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @artisans.each do |artisan| %>
      <tr>
        <td><%= link_to artisan.id, artisan_path(artisan) %></td>
        <td><%= artisan.description %></td>
        <td><%= artisan.firstname %></td>
        <td><%= artisan.lastname %></td>
        <td><%= artisan.society %></td>
        <td><%= artisan.phone %></td>
        <td><%= artisan.location %></td>
        <td><%=l artisan.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_artisan_path(artisan), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      artisan_path(artisan),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_artisan_path,
            :class => 'btn btn-primary' %>

app/views/artisans/new.html.erb
<%- model_class = Artisan -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/artisans/show.html.erb
<%- model_class = Artisan -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @artisan.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:firstname) %>:</strong></dt>
  <dd><%= @artisan.firstname %></dd>
  <dt><strong><%= model_class.human_attribute_name(:lastname) %>:</strong></dt>
  <dd><%= @artisan.lastname %></dd>
    <dt><strong><%= model_class.human_attribute_name(:society) %>:</strong></dt>
  <dd><%= @artisan.lastname %></dd>
  <dt><strong><%= model_class.human_attribute_name(:phone) %>:</strong></dt>
  <dd><%= @artisan.phone %></dd>
  <dt><strong><%= model_class.human_attribute_name(:location) %>:</strong></dt>
  <dd><%= @artisan.location %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              artisans_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_artisan_path(@artisan), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              artisan_path(@artisan),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/home/index.html.erb
<h1>Coucou Inès!!</h1>
<p>Trop chowwww</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "FixMenBackk" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">FixMenBackk</a>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Eridanis 2015</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => "form-horizontal user" } do |f| %>

    <% if @user.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :firstname, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :firstname, :class => 'form-control' %>
    </div>
    <%= error_span(@user[:firstname]) %>
  </div>
  <div class="control-group">
    <%= f.label :lastname, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :lastname, :class => 'form-control' %>
    </div>
    <%= error_span(@user[:lastname]) %>
  </div>
  <div class="control-group">
    <%= f.label :phone, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :phone, :class => 'form-control' %>
    </div>
    <%= error_span(@user[:phone]) %>
  </div>
  <div class="control-group">
    <%= f.label :mail, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :mail, :class => 'form-control' %>
    </div>
    <%= error_span(@user[:mail]) %>
  </div>
  <div class="control-group">
    <%= f.label :location, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :location, :class => 'form-control' %>
    </div>
    <%= error_span(@user[:location]) %>
  </div>
  <div class="control-group">
    <%= f.label :cardnumber, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :cardnumber, :class => 'form-control' %>
    </div>
    <%= error_span(@user[:cardnumber]) %>
  </div>
  <div class="control-group">
    <%= f.label :carddate, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :carddate, :class => 'form-control' %>
    </div>
    <%= error_span(@user[:carddate]) %>
  </div>
  <div class="control-group">
    <%= f.label :cardback, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :cardback, :class => 'form-control' %>
    </div>
    <%= error_span(@user[:cardback]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            users_path, :class => 'btn btn-default' %>

<% end %>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:firstname) %></th>
      <th><%= model_class.human_attribute_name(:lastname) %></th>
      <th><%= model_class.human_attribute_name(:phone) %></th>
      <th><%= model_class.human_attribute_name(:mail) %></th>
      <th><%= model_class.human_attribute_name(:location) %></th>
      <th><%= model_class.human_attribute_name(:cardnumber) %></th>
      <th><%= model_class.human_attribute_name(:carddate) %></th>
      <th><%= model_class.human_attribute_name(:cardback) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.id, user_path(user) %></td>
        <td><%= user.firstname %></td>
        <td><%= user.lastname %></td>
        <td><%= user.phone %></td>
        <td><%= user.mail %></td>
        <td><%= user.location %></td>
        <td><%= user.cardnumber %></td>
        <td><%= user.carddate %></td>
        <td><%= user.cardback %></td>
        <td><%=l user.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_path(user), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_path(user),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %>

app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:firstname) %>:</strong></dt>
  <dd><%= @user.firstname %></dd>
  <dt><strong><%= model_class.human_attribute_name(:lastname) %>:</strong></dt>
  <dd><%= @user.lastname %></dd>
  <dt><strong><%= model_class.human_attribute_name(:phone) %>:</strong></dt>
  <dd><%= @user.phone %></dd>
  <dt><strong><%= model_class.human_attribute_name(:mail) %>:</strong></dt>
  <dd><%= @user.mail %></dd>
  <dt><strong><%= model_class.human_attribute_name(:location) %>:</strong></dt>
  <dd><%= @user.location %></dd>
  <dt><strong><%= model_class.human_attribute_name(:cardnumber) %>:</strong></dt>
  <dd><%= @user.cardnumber %></dd>
  <dt><strong><%= model_class.human_attribute_name(:carddate) %>:</strong></dt>
  <dd><%= @user.carddate %></dd>
  <dt><strong><%= model_class.human_attribute_name(:cardback) %>:</strong></dt>
  <dd><%= @user.cardback %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              users_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_path(@user), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_path(@user),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>